"""
BUILD / SYNC DASHBOARD  (single source of truth)
================================================
Fixes the "host is still same" / "showing it wrong" class of bugs by making the
JSON files in dashboard_data/ the ONE source of truth and regenerating everything
else from them with a single command.

WHAT IT DOES
  1. Regenerates each  dashboard_data/<name>.js  window-global bundle from its
     matching  dashboard_data/<name>.json  (so .js can never drift from .json).
  2. Copies the root  event_trading_dashboard.html  ->  docs/  (the folder the
     GitHub Pages host actually serves), so local == host.
  3. Copies every  dashboard_data/*.json  and  *.js  ->  docs/dashboard_data/.
  4. Validates that every JSON parses before writing anything.

USAGE
  python build_dashboard.py            # build + sync (run this before every push)
  python build_dashboard.py --check    # verify everything is in sync; exit 1 if not
                                        # (use in CI / a pre-push hook)

ADDITIVE: new tooling file. Changes no source data — only regenerates derived
artifacts (.js bundles) and mirrors root -> docs.
"""
import sys, os, json, shutil, argparse

BASE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(BASE, 'dashboard_data')
DOCS = os.path.join(BASE, 'docs')
DOCS_DATA = os.path.join(DOCS, 'dashboard_data')
HTML = 'event_trading_dashboard.html'

# json base name -> (window global, [extra alias lines appended after the assignment])
BUNDLES = [
    ('event_dashboard_data',            'EVENT_DASHBOARD_DATA',
        ['window.DASHBOARD_DATA = window.EVENT_DASHBOARD_DATA;']),
    ('fo_stocks_211',                   'FO_STOCKS_211',                 []),
    ('live_corporate_events',           'LIVE_CORPORATE_EVENTS',         []),
    ('nifty_futures_holiday_behaviour', 'NIFTY_HOLIDAY_BEHAVIOUR_DATA',  []),
    ('rbi_policy_behaviour',            'RBI_POLICY_DATA',               []),
]

# json files that are fetched at runtime (validated, mirrored, but no .js bundle)
FETCH_ONLY = ['holidays_dataset', 'quarters_dataset', 'upcoming_nifty50_results']


def _load_json(path):
    with open(path, encoding='utf-8') as f:
        return json.load(f)


def _js_text(global_name, obj, aliases):
    payload = json.dumps(obj, ensure_ascii=False, separators=(', ', ': '))
    lines = ['window.%s = %s;' % (global_name, payload)]
    lines += list(aliases)
    return '\n'.join(lines) + '\n'


def _read(path):
    with open(path, encoding='utf-8') as f:
        return f.read()


def validate():
    """Parse every JSON file; raise on the first bad one."""
    problems = []
    names = [b[0] for b in BUNDLES] + FETCH_ONLY
    for name in names:
        p = os.path.join(DATA, name + '.json')
        if not os.path.exists(p):
            problems.append('MISSING: dashboard_data/%s.json' % name)
            continue
        try:
            _load_json(p)
        except Exception as e:
            problems.append('BAD JSON: %s -> %s' % (name + '.json', e))
    return problems


def build():
    print('== BUILD / SYNC DASHBOARD ==')
    problems = validate()
    if problems:
        print('\n'.join('  [X] ' + p for p in problems))
        print('\nAborted — fix the JSON above first. Nothing was written.')
        sys.exit(1)

    # 1. regenerate .js bundles from .json
    for name, g, aliases in BUNDLES:
        obj = _load_json(os.path.join(DATA, name + '.json'))
        js = _js_text(g, obj, aliases)
        with open(os.path.join(DATA, name + '.js'), 'w', encoding='utf-8') as f:
            f.write(js)
        print('  [js] dashboard_data/%s.js  <-  %s.json  (window.%s%s)'
              % (name, name, g, ', +%d alias' % len(aliases) if aliases else ''))

    # 2. root html -> docs
    os.makedirs(DOCS, exist_ok=True)
    shutil.copy2(os.path.join(BASE, HTML), os.path.join(DOCS, HTML))
    print('  [html] docs/%s  <-  %s' % (HTML, HTML))

    # 3. mirror all data (.json + .js) into docs/dashboard_data
    os.makedirs(DOCS_DATA, exist_ok=True)
    copied = 0
    for fn in sorted(os.listdir(DATA)):
        if fn.endswith('.json') or fn.endswith('.js'):
            shutil.copy2(os.path.join(DATA, fn), os.path.join(DOCS_DATA, fn))
            copied += 1
    print('  [data] docs/dashboard_data/  <-  %d files mirrored' % copied)

    print('\nDONE. Local and host (docs/) are now in sync. '
          'Commit & push docs/ to update GitHub Pages.')


def check():
    """Verify everything is in sync WITHOUT writing. Exit 1 on any drift."""
    print('== CHECK (in-sync verification) ==')
    problems = validate()

    # each .js must equal the freshly-regenerated bytes from its .json
    for name, g, aliases in BUNDLES:
        jp, sp = os.path.join(DATA, name + '.json'), os.path.join(DATA, name + '.js')
        if not os.path.exists(sp):
            problems.append('MISSING .js: dashboard_data/%s.js' % name); continue
        expect = _js_text(g, _load_json(jp), aliases)
        if _read(sp) != expect:
            problems.append('OUT OF SYNC: %s.js differs from %s.json (run build)' % (name, name))

    # root html must equal docs html
    rh, dh = os.path.join(BASE, HTML), os.path.join(DOCS, HTML)
    if not os.path.exists(dh):
        problems.append('MISSING: docs/%s' % HTML)
    elif _read(rh) != _read(dh):
        problems.append('OUT OF SYNC: docs/%s differs from root (run build)' % HTML)

    # docs data mirror must match
    for fn in os.listdir(DATA):
        if fn.endswith('.json') or fn.endswith('.js'):
            dp = os.path.join(DOCS_DATA, fn)
            if not os.path.exists(dp):
                problems.append('MISSING in docs: dashboard_data/%s' % fn)
            elif _read(os.path.join(DATA, fn)) != _read(dp):
                problems.append('OUT OF SYNC: docs/dashboard_data/%s' % fn)

    if problems:
        print('\n'.join('  [X] ' + p for p in problems))
        print('\nNOT IN SYNC — run:  python build_dashboard.py')
        sys.exit(1)
    print('  [OK] all .js match .json, root html == docs html, data mirror matches.')
    print('IN SYNC.')


if __name__ == '__main__':
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true',
                    help='verify in-sync without writing (exit 1 on drift)')
    args = ap.parse_args()
    check() if args.check else build()
