"""
scrap.py
===============================================================================
NSE CORPORATE DISCLOSURES SCRAPER  —  NSE F&O universe, append-only archive.

Runs twice daily from Task Scheduler (run_daily_scraper.bat) and grows an
archive of 38 NSE disclosure feeds under output_excels/.

WHAT CHANGED (2026-08-07 — universe widened to the F&O list)
------------------------------------------------------------
The universe was the Nifty 50. It is now the ~208 derivatives-eligible NSE
underlyings in fno_derivatives_list.csv (regenerate with build_universe_csv.py).

Rationale: the straddle terminal can only express an event as a trade on a name
that HAS an option chain. An earnings date on a non-F&O stock is unactionable;
the other 158 F&O names were being dropped even though they are exactly the
universe the dashboard charts.

Consequences, so they are not a surprise:
  * ~4x the HTTP round-trips (~2,300 vs ~550). Expect a materially longer run.
  * The two big feeds scale with the universe. On the 50-name run they held
    01_Dashboard_Summary 94,757 rows and 02_Announcements 78,841; at 208 names
    they land near 395k and 330k. Both fit under Excel's 1,048,576-row ceiling
    today, but ROW_WARN_THRESHOLD will start firing as they accumulate — that
    warning is the signal to move those two feeds to parquet.
  * Market-wide feeds (12, 20, 25, 26, 27, 30, 31, 37) filter against the
    universe set, so they widen automatically.
  * ISIN is blank for the 158 new names — only 08_Company_Directory's offline
    fallback reads it, and it tolerates blanks. Nothing else uses ISIN.

PRIOR PASS (2026-07-27 hardening)
---------------------------------
 1. FAILURE IS NOW VISIBLE.  Previously a network failure, a response-shape
    mismatch and a genuinely-empty feed all collapsed into `pd.DataFrame()`
    and every one of them logged [SUCCESS].  14 of 38 feeds were dead and the
    log said 0 errors.  Each feed now reports OK / EMPTY / FAIL separately,
    and the run ends with a summary table + machine-readable _run_status.json.

 2. A FAILED FETCH NEVER TOUCHES THE ARCHIVE.  Before, a bad response wrote an
    empty frame over accumulated history.  save_feed() now refuses to write
    unless the fetch actually succeeded.

 3. RESPONSE SHAPES ARE NORMALISED.  NSE returns bare lists, {"data": [...]},
    {"rows": [...]} and single dicts depending on the endpoint, and changes
    them over time.  normalize_rows() accepts all of them, so a shape change
    no longer silently empties a feed.

 4. DEDUPE KEYS PER FEED.  Only 4 of 39 saves passed a dedupe key; the rest
    de-duplicated on ALL columns, which fails the moment a volatile field
    (difference / fileSize / sysTime) drifts between fetches.  That put
    107,135 duplicate rows into 02_Announcements (58% of the file).
    DEDUPE_KEYS now assigns a natural key to every feed, and the all-column
    fallback ignores known-volatile columns.

 5. POINT-IN-TIME.  Every row is stamped `fetched_at` — what we knew, when.
    (Excluded from dedupe, or every row would look new on every run.)

 6. 13_Financial_Results was truncated to 2007-2012 because the endpoint was
    called without a period window.  Now fetched per financial year.

 7. 36_Concall only scanned symbols[:15] — 70% of the Nifty 50 was skipped.
    It is now derived from the announcements already fetched (all 50 symbols,
    and 15 fewer HTTP round-trips).

RUN
    python scrap.py                 # full run
    python scrap.py --dry-run       # fetch + report, write nothing
===============================================================================
"""

import json
import os
import sys
import time
from datetime import datetime
from urllib.parse import quote

import pandas as pd
import requests
from openpyxl.cell.cell import ILLEGAL_CHARACTERS_RE

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "*/*",
    "Accept-Language": "en-US,en;q=0.9",
    "Referer": "https://www.nseindia.com/companies-listing/corporate-filings-announcements",
}

# Self-referential: this folder was moved from D:\share_live\action_cop to
# D:\behaviour analysis\action_cop. Resolving paths relative to this file's own
# location (instead of the old hardcoded D:\share_live\...) means the scraper
# writes to its OWN output_excels/ no matter where the folder lives, and a
# future move doesn't silently re-split the archive across two locations.
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_DIR = os.path.join(BASE_DIR, "output_excels")
# The scrape universe. fno_derivatives_list.csv is generated by
# build_universe_csv.py; the Nifty 50 file is kept only as a fallback so a
# missing/renamed universe file degrades to the old behaviour instead of
# crashing the scheduled task.
UNIVERSE_CSV = os.path.join(BASE_DIR, "fno_derivatives_list.csv")
FALLBACK_CSV = os.path.join(BASE_DIR, "ind_nifty50list.csv")
STATUS_FILE = os.path.join(OUTPUT_DIR, "_run_status.json")

RUN_TS = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
DRY_RUN = "--dry-run" in sys.argv

# Excel hard limit is 1,048,576 rows. Warn well before we get there.
ROW_WARN_THRESHOLD = 800_000

# Columns that change between fetches for the SAME record. They must never take
# part in de-duplication or every row looks new on every run.
VOLATILE_COLS = {
    "fetched_at", "difference", "diff", "timeDifference", "TimeDifference",
    "timeTaken", "sysTime", "systym", "systemDate", "TimeStamp", "time",
    "attFileSize", "fileSize", "xbrlFileSize", "ixbrlFileSize",
    "data", "msg",
}

# Natural key per feed — the columns that identify one real-world record.
DEDUPE_KEYS = {
    "01_Dashboard_Summary.xlsx": ["symbol", "date", "subject", "desc", "attchmntFile"],
    "02_Announcements.xlsx": ["seq_id"],
    "03_Announcements_XBRL.xlsx": ["seq_id"],
    "04_Board_Meetings.xlsx": ["bm_symbol", "bm_date", "bm_purpose", "bm_desc"],
    "05_Corporate_Actions.xlsx": ["symbol", "exDate", "recDate", "subject"],
    "06_Annual_Reports.xlsx": ["symbol", "fromYr", "toYr", "fileName"],
    "07_BRSR_Reports.xlsx": ["symbol", "fromYr", "toYr", "fileName"],
    "08_Company_Directory.xlsx": ["symbol"],
    "09_Corporate_Governance.xlsx": ["symbol", "submissionDate"],
    "10_Corporate_Information.xlsx": ["symbol"],
    "11_Daily_Buy_Back.xlsx": ["symbol", "recordDate"],
    "12_Event_Calendar.xlsx": ["symbol", "date", "purpose"],
    "13_Financial_Results.xlsx": ["symbol", "fromDate", "toDate", "audited",
                                  "consolidated", "seqNumber", "resultPeriod"],
    "14_Financial_Results_Comparison.xlsx": ["symbol", "fromDate", "toDate"],
    "15_Further_Issues_XBRL_Filings.xlsx": ["symbol", "submissionDate"],
    "16_Insider_Trading_PIT.xlsx": ["did", "symbol", "acqName", "acqfromDt",
                                    "secAcq", "personCategory"],
    "17_Insider_Trading_Plan.xlsx": ["did", "symbol", "date", "name"],
    "18_Investor_Complaints.xlsx": ["companyName", "broadcastDate"],
    "19_Issue_Offer_Documents.xlsx": ["symbol", "issueName", "issueStartDate"],
    "20_Promoter_Encumbrance_Details.xlsx": ["seqId"],
    "21_Related_Party_Transactions.xlsx": ["seqNum"],
    "22_SAST_Regulations.xlsx": ["application_no"],
    "23_Secretarial_Compliance.xlsx": ["symbol", "submissionDate"],
    "24_Share_Transfers.xlsx": ["symbol", "date"],
    "25_Shareholders_Meetings.xlsx": ["symbol", "date", "desc"],
    "26_Shareholding_Pattern.xlsx": ["recordId"],
    "27_Shareholding_Pattern_SDD.xlsx": ["symbol", "date"],
    "28_Statement_of_Deviation.xlsx": ["sod_id"],
    "29_Audit_Qualification_Impact.xlsx": ["symbol", "submissionDate"],
    "30_System_Driven_Disclosures_PIT.xlsx": ["symbol", "date", "name"],
    "31_System_Driven_Disclosures_SAST.xlsx": ["symbol", "date", "name"],
    "32_Voting_Results.xlsx": ["symbol", "metadata"],
    "33_FII_DII_Trading_Activity.xlsx": ["date", "category"],
    "34_Bulk_Deals.xlsx": ["Date", "Symbol", "Client Name", "Buy/Sell",
                           "Quantity Traded", "Trade Price / Wght. Avg. Price"],
    "35_Block_Deals.xlsx": ["Date", "Symbol", "Client Name", "Buy/Sell",
                            "Quantity Traded", "Trade Price / Wght. Avg. Price"],
    "36_Concall_Transcripts_Presentations.xlsx": ["Symbol", "Date", "Description"],
    "37_Credit_Rating_Reports.xlsx": ["symbol", "creditAgencyName",
                                      "dateOfCurrentCredit", "ratingAssigned",
                                      "creditRating"],
    "38_Super_Investor_Institutional_Holdings.xlsx": ["recordId"],
}

# feed name -> (status, rows_fetched, rows_in_archive, note)
RUN_STATUS = {}


# ---------------------------------------------------------------------------
# Session / HTTP
# ---------------------------------------------------------------------------
_SESSION = None


def get_session(force=False):
    """Persistent NSE session, cookie-warmed. Module-level so that a re-warm
    triggered deep inside a fetch actually survives for later calls (the old
    code rebound a local name and threw the new session away)."""
    global _SESSION
    if _SESSION is None or force:
        s = requests.Session()
        try:
            s.get("https://www.nseindia.com", headers=HEADERS, timeout=10)
            time.sleep(1)
            s.get("https://www.nseindia.com/companies-listing/corporate-filings-announcements",
                  headers=HEADERS, timeout=10)
            time.sleep(1)
        except Exception as e:
            print(f"[WARN] session init: {type(e).__name__}: {e}")
        _SESSION = s
    return _SESSION


def fetch_json(url, params=None, retries=3, delay=0.4):
    """Fetch JSON from NSE.

    Returns (ok: bool, payload_or_error). The bool is the whole point — the old
    version returned None for 'request failed', 'body was not JSON' and 'NSE
    said nothing', which is why 14 feeds died silently.
    """
    last = "no attempt made"
    for attempt in range(retries):
        session = get_session()
        try:
            resp = session.get(url, headers=HEADERS, params=params, timeout=15)
            if resp.status_code == 200:
                try:
                    return True, resp.json()
                except ValueError:
                    last = f"HTTP 200 but body was not JSON ({len(resp.content)} bytes)"
            elif resp.status_code in (401, 403):
                last = f"HTTP {resp.status_code} (session expired)"
                get_session(force=True)
            else:
                last = f"HTTP {resp.status_code}"
        except Exception as e:
            last = f"{type(e).__name__}: {e}"
        time.sleep(delay * (attempt + 1))
    return False, last


def normalize_rows(payload):
    """NSE hands back a bare list, {'data': [...]}, {'rows': [...]} or a single
    dict depending on the endpoint — and changes shape between releases.
    Accept all of them and always return a list of dicts."""
    if payload is None:
        return []
    if isinstance(payload, list):
        return [r for r in payload if isinstance(r, dict)]
    if isinstance(payload, dict):
        for key in ("data", "rows", "records", "result", "value", "list"):
            v = payload.get(key)
            if isinstance(v, list):
                return [r for r in v if isinstance(r, dict)]
        # A flat dict of scalars is itself a single record.
        if payload and all(not isinstance(v, (dict, list)) for v in payload.values()):
            return [payload]
    return []


# ---------------------------------------------------------------------------
# Fetch helpers
# ---------------------------------------------------------------------------
def harvest(url, *, universe_set=None, params=None):
    """Single-call, market-wide feed -> (DataFrame, ok, note).

    `universe_set` narrows a market-wide response to the symbols we scrape. It
    is matched case-insensitively on a stripped symbol — NSE returns the same
    ticker with stray whitespace and mixed case across endpoints, and an exact
    `.isin()` silently drops those rows.
    """
    ok, payload = fetch_json(url, params=params)
    if not ok:
        return pd.DataFrame(), False, str(payload)
    rows = normalize_rows(payload)
    if not rows:
        shape = type(payload).__name__
        keys = list(payload)[:6] if isinstance(payload, dict) else ""
        return pd.DataFrame(), True, f"no rows (payload={shape} {keys})"
    df = pd.DataFrame(rows)
    note = f"{len(df)} rows"
    if universe_set and "symbol" in df.columns:
        before = len(df)
        df = df[df["symbol"].astype(str).str.strip().str.upper().isin(universe_set)]
        note = f"{len(df)}/{before} rows after F&O universe filter"
    return df, True, note


def harvest_symbol_wise(url_template, symbols, symbol_map, key_in_resp=None,
                        delay=0.2, params_fn=None):
    """Per-symbol feed -> (DataFrame, ok, note).

    'ok' is False only if EVERY symbol failed — that means the endpoint or the
    session is broken, not that the companies have no filings.
    """
    aggregated, failures = [], 0
    for i, sym in enumerate(symbols):
        # The symbol goes into a query string, so it MUST be percent-encoded.
        # M&M and GVT&D carry a literal '&': unencoded, `symbol=M&M` parses as
        # symbol="M" plus a stray "M" param, NSE answers 200 with an empty list,
        # and the feed logs SUCCESS. M&M has been returning zero rows on every
        # per-symbol feed for this reason. Verified 2026-08-07: raw -> 0 rows,
        # encoded -> 20 rows, for both symbols.
        url = url_template.format(symbol=quote(sym, safe=""))
        params = params_fn(sym) if params_fn else None
        ok, payload = fetch_json(url, params=params, delay=delay)
        if not ok:
            failures += 1
        else:
            items = payload.get(key_in_resp) if (key_in_resp and isinstance(payload, dict)) else None
            if not isinstance(items, list):
                items = normalize_rows(payload)
            for item in items:
                if isinstance(item, dict):
                    if "symbol" not in item and "Symbol" not in item:
                        item["symbol"] = sym
                    if "company_name" not in item and "Company Name" not in item:
                        item["company_name"] = symbol_map.get(sym, sym)
                    aggregated.append(item)
        if (i + 1) % 25 == 0:
            get_session(force=True)
        time.sleep(delay)

    total = len(symbols)
    if failures == total:
        return pd.DataFrame(), False, f"all {total} symbol requests failed"
    note = f"{len(aggregated)} rows from {total - failures}/{total} symbols"
    if failures:
        note += f" ({failures} failed)"
    return (pd.DataFrame(aggregated) if aggregated else pd.DataFrame()), True, note


# ---------------------------------------------------------------------------
# Persistence
# ---------------------------------------------------------------------------
def clean_dataframe(df):
    if df is None or df.empty:
        return df
    df = df.dropna(how="all", axis=1)
    for col in df.columns:
        df[col] = df[col].apply(lambda x: str(x) if isinstance(x, (dict, list)) else x)
    # NSE announcement text occasionally carries raw control characters (e.g. a
    # literal vertical-tab in a GAIL filing) that openpyxl refuses to write --
    # it raises IllegalCharacterError and the whole feed fails save_feed()
    # entirely, with 01_Dashboard_Summary and 02_Announcements hitting this
    # repeatedly. Strip them the same way openpyxl's own writer would reject
    # them, instead of losing the whole feed over one bad cell.
    for col in df.select_dtypes(include="object").columns:
        df[col] = df[col].apply(
            lambda x: ILLEGAL_CHARACTERS_RE.sub("", x) if isinstance(x, str) else x
        )
    return df


def _dedupe(df, filename):
    """De-duplicate on the feed's natural key, else on all non-volatile columns.

    The key is compared as normalised TEXT, not on raw dtypes. Excel round-trips
    change types — seq_id comes back from disk as int64 but arrives from the API
    as str — so a plain drop_duplicates() sees 12345 and "12345" as different
    records and the archive silently doubles on every run. That is what put
    107k phantom rows in 02_Announcements.
    """
    if df.empty:
        return df
    key = [c for c in DEDUPE_KEYS.get(filename, []) if c in df.columns]
    if not key:
        key = [c for c in df.columns if c not in VOLATILE_COLS]
    if not key:
        return df
    # Trailing ".0" only: Excel stores an integer id as float, so 12345 returns
    # as "12345.0" while the API sends "12345". Applied to both sides equally.
    norm = df[key].astype(str).apply(
        lambda s: s.str.strip().str.replace(r"\.0$", "", regex=True))
    return df[~norm.duplicated(keep="last")]


def save_feed(df, filename, sheet, ok, note=""):
    """Merge a fetch into the archive.

    Contract:
      ok=False -> the archive is left EXACTLY as it was. A failed fetch must
                  never be able to shrink or blank accumulated history.
      ok=True  -> append, stamp fetched_at, de-duplicate on the natural key.
    """
    feed = filename[:-5]
    filepath = os.path.join(OUTPUT_DIR, filename)

    # Read the archive ONCE. The old code called pd.read_excel twice — once to
    # count rows for the log line, once again to merge. That was tolerable on the
    # 50-name archives; on the F&O universe 01_Dashboard_Summary and
    # 02_Announcements are ~4x bigger and the duplicate read costs minutes a run.
    existing, read_err = None, None
    if os.path.exists(filepath):
        try:
            existing = clean_dataframe(pd.read_excel(filepath))
            # A feed that has only ever been empty holds a single "Message"
            # placeholder column — that is not history, so do not merge it.
            if existing is not None and "Message" in existing.columns and len(existing.columns) == 1:
                existing = pd.DataFrame()
        except Exception as e:
            read_err = f"{type(e).__name__}: {e}"
    existing_rows = 0 if existing is None else len(existing)

    if not ok:
        print(f"[FETCH-FAIL] {feed}: {note} — archive left untouched ({existing_rows} rows)")
        RUN_STATUS[feed] = {"status": "FAIL", "fetched": 0,
                            "archive_rows": existing_rows, "note": note}
        return None

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    df = clean_dataframe(df)
    fetched = 0 if df is None or df.empty else len(df)

    if fetched:
        df = df.copy()
        df["fetched_at"] = RUN_TS

    # Merge with what is already on disk.
    if read_err is not None:
        print(f"[WARN] {feed}: could not read existing archive ({read_err}) "
              f"— aborting write to avoid data loss")
        RUN_STATUS[feed] = {"status": "FAIL", "fetched": fetched,
                            "archive_rows": existing_rows,
                            "note": f"archive unreadable: {read_err}"}
        return None
    if existing is not None and not existing.empty:
        df = pd.concat([existing, df], ignore_index=True) if fetched else existing

    if df is None or df.empty:
        print(f"[EMPTY] {feed}: {note}")
        RUN_STATUS[feed] = {"status": "EMPTY", "fetched": 0,
                            "archive_rows": existing_rows, "note": note}
        return None

    before = len(df)
    df = _dedupe(df, filename)
    dropped = before - len(df)

    if len(df) > ROW_WARN_THRESHOLD:
        print(f"[WARN] {feed}: {len(df):,} rows — approaching Excel's 1,048,576 limit. "
              f"Move this feed to parquet.")

    if DRY_RUN:
        print(f"[DRY-RUN] {feed}: would write {len(df):,} rows "
              f"(+{fetched} fetched, -{dropped} dupes) — {note}")
        RUN_STATUS[feed] = {"status": "OK", "fetched": fetched,
                            "archive_rows": len(df), "note": note + " [dry-run]"}
        return None

    for attempt in range(3):
        try:
            with pd.ExcelWriter(filepath, engine="openpyxl") as writer:
                df.to_excel(writer, sheet_name=sheet[:31], index=False)
                ws = writer.sheets[sheet[:31]]
                # Size columns from the header + a sample, not every cell. The old
                # version scanned all ~2.2M cells of 02_Announcements on every run.
                sample = df.head(200)
                for i, col in enumerate(df.columns, start=1):
                    # An all-null column gives NaN here, and NaN is truthy, so
                    # `int(x or 0)` raises. Guard explicitly.
                    m = sample[col].astype(str).str.len().max()
                    width = max(len(str(col)), int(m) if pd.notna(m) else 0)
                    ws.column_dimensions[ws.cell(row=1, column=i).column_letter].width = \
                        min(max(width + 3, 12), 60)
            gained = len(df) - existing_rows
            print(f"[OK] {feed}: {len(df):,} rows in archive "
                  f"(+{gained} new, {fetched} fetched, {dropped} dupes dropped) — {note}")
            RUN_STATUS[feed] = {"status": "OK", "fetched": fetched,
                                "archive_rows": len(df), "new": gained, "note": note}
            return filepath
        except PermissionError:
            time.sleep(1.5)
            if attempt == 2:
                print(f"[FILE-LOCK] {feed}: file is open in Excel — NOT saved")
                RUN_STATUS[feed] = {"status": "FAIL", "fetched": fetched,
                                    "archive_rows": existing_rows,
                                    "note": "file locked (open in Excel?)"}
        except Exception as e:
            print(f"[WRITE-FAIL] {feed}: {type(e).__name__}: {e}")
            RUN_STATUS[feed] = {"status": "FAIL", "fetched": fetched,
                                "archive_rows": existing_rows, "note": str(e)}
            break
    return None


# ---------------------------------------------------------------------------
def load_universe(csv_path=UNIVERSE_CSV):
    """Load the scrape universe -> (symbols, name_map, isin_map).

    Only 'Symbol' and 'Company Name' are required. ISIN is optional and blank
    for the F&O names we do not hold one for — a guessed ISIN would silently
    mis-join downstream, so the column is allowed to be empty and the one
    consumer (08_Company_Directory's offline fallback) handles that.
    """
    path = csv_path if os.path.exists(csv_path) else FALLBACK_CSV
    if path != csv_path:
        print(f"[WARN] {csv_path} not found — falling back to {path}. "
              f"Run build_universe_csv.py to regenerate the F&O universe.")

    df = pd.read_csv(path, dtype=str).fillna("")
    missing = {"Symbol", "Company Name"} - set(df.columns)
    if missing:
        raise ValueError(f"{path}: missing required column(s) {sorted(missing)}")

    df["Symbol"] = df["Symbol"].str.strip().str.upper()
    df = df[df["Symbol"] != ""].drop_duplicates(subset="Symbol", keep="first")

    symbols = df["Symbol"].tolist()
    symbol_map = dict(zip(symbols, df["Company Name"].str.strip()))
    isin_col = df["ISIN Code"].str.strip() if "ISIN Code" in df.columns else ""
    isin_map = dict(zip(symbols, isin_col)) if len(isin_col) else {}
    return symbols, symbol_map, isin_map


API = "https://www.nseindia.com/api"


def run_scraper():
    print("=" * 70)
    print(f"NSE CORPORATE DISCLOSURES SCRAPER — {RUN_TS}"
          + ("  [DRY RUN]" if DRY_RUN else ""))
    print("=" * 70)
    symbols, symbol_map, isin_map = load_universe()
    universe_set = set(symbols)
    print(f"Universe: {len(symbols)} NSE F&O underlyings "
          f"({os.path.basename(UNIVERSE_CSV)})\n")
    get_session()

    def step(n, title):
        print(f"\n--- [{n}/38] {title} ---")

    # -- 1. Dashboard / filings summary --------------------------------------
    step(1, "Dashboard / Corporate Filings Summary")
    df, ok, note = harvest_symbol_wise(f"{API}/quick-links-corporate?symbol={{symbol}}",
                                       symbols, symbol_map)
    save_feed(df, "01_Dashboard_Summary.xlsx", "Dashboard Summary", ok, note)

    # -- 2. Announcements ----------------------------------------------------
    step(2, "Corporate Announcements")
    df_ann, ann_ok, note = harvest_symbol_wise(
        f"{API}/corporate-announcements?index=equities&symbol={{symbol}}",
        symbols, symbol_map)
    save_feed(df_ann, "02_Announcements.xlsx", "Announcements", ann_ok, note)

    # -- 3. Announcements XBRL (derived) -------------------------------------
    step(3, "Announcements XBRL (derived from #2)")
    if ann_ok and not df_ann.empty and "hasXbrl" in df_ann.columns:
        sub = df_ann[df_ann["hasXbrl"] == True]  # noqa: E712
        save_feed(sub, "03_Announcements_XBRL.xlsx", "Announcements XBRL",
                  True, f"{len(sub)} of {len(df_ann)} announcements carry XBRL")
    else:
        save_feed(pd.DataFrame(), "03_Announcements_XBRL.xlsx", "Announcements XBRL",
                  ann_ok, "source feed #2 unavailable" if not ann_ok else "no hasXbrl column")

    # -- 4. Board meetings ---------------------------------------------------
    step(4, "Board Meetings")
    df, ok, note = harvest_symbol_wise(
        f"{API}/corporate-board-meetings?index=equities&symbol={{symbol}}",
        symbols, symbol_map)
    save_feed(df, "04_Board_Meetings.xlsx", "Board Meetings", ok, note)

    # -- 5. Corporate actions ------------------------------------------------
    step(5, "Corporate Actions")
    df, ok, note = harvest_symbol_wise(
        f"{API}/corporates-corporateActions?index=equities&symbol={{symbol}}",
        symbols, symbol_map)
    save_feed(df, "05_Corporate_Actions.xlsx", "Corporate Actions", ok, note)

    # -- 6. Annual reports ---------------------------------------------------
    step(6, "Annual Reports")
    df_ar, ar_ok, note = harvest_symbol_wise(
        f"{API}/annual-reports?index=equities&symbol={{symbol}}",
        symbols, symbol_map, key_in_resp="data")
    save_feed(df_ar, "06_Annual_Reports.xlsx", "Annual Reports", ar_ok, note)

    # -- 7. BRSR (derived from #6) -------------------------------------------
    step(7, "BRSR Reports (derived from #6)")
    if ar_ok and not df_ar.empty:
        col = next((c for c in ("fileName", "fileNm", "attachment") if c in df_ar.columns), None)
        if col:
            sub = df_ar[df_ar[col].astype(str).str.lower()
                        .str.contains("brsr|sustainability|business responsibility",
                                      na=False, regex=True)]
            save_feed(sub, "07_BRSR_Reports.xlsx", "BRSR Reports", True,
                      f"{len(sub)} BRSR of {len(df_ar)} annual reports (matched on '{col}')")
        else:
            save_feed(pd.DataFrame(), "07_BRSR_Reports.xlsx", "BRSR Reports", True,
                      f"no filename column in #6; have {list(df_ar.columns)[:8]}")
    else:
        save_feed(pd.DataFrame(), "07_BRSR_Reports.xlsx", "BRSR Reports", ar_ok,
                  "source feed #6 unavailable")

    # -- 8. Company directory ------------------------------------------------
    step(8, "Company Directory")
    df, ok, note = harvest(f"{API}/corporate-listing-directory?index=equity",
                           universe_set=universe_set)
    if ok and df.empty:
        # isin_map is sparse for the F&O names — emit the row without an ISIN
        # rather than skipping the company or inventing an identifier.
        df = pd.DataFrame([{"symbol": s, "company_name": symbol_map.get(s, s),
                            "isin": isin_map.get(s, "")}
                           for s in symbols])
        note = f"NSE directory empty — rebuilt from local universe CSV ({len(df)} symbols)"
    save_feed(df, "08_Company_Directory.xlsx", "Company Directory", ok, note)

    # -- 9. Corporate governance ---------------------------------------------
    step(9, "Corporate Governance")
    df, ok, note = harvest_symbol_wise(
        f"{API}/corporate-governance?index=equities&symbol={{symbol}}",
        symbols, symbol_map)
    save_feed(df, "09_Corporate_Governance.xlsx", "Corporate Governance", ok, note)

    # -- 10. Corporate information -------------------------------------------
    step(10, "Corporate Information")
    df, ok, note = harvest_symbol_wise(f"{API}/equity-metainfo?symbol={{symbol}}",
                                       symbols, symbol_map)
    save_feed(df, "10_Corporate_Information.xlsx", "Corporate Information", ok, note)

    # -- 11. Daily buy-back ---------------------------------------------------
    step(11, "Daily Buy Back")
    df, ok, note = harvest(f"{API}/corporates-daily-buyback?index=equities",
                           universe_set=universe_set)
    save_feed(df, "11_Daily_Buy_Back.xlsx", "Daily Buy Back", ok, note)

    # -- 12. Event calendar ---------------------------------------------------
    step(12, "Event Calendar")
    df, ok, note = harvest(f"{API}/event-calendar", universe_set=universe_set)
    save_feed(df, "12_Event_Calendar.xlsx", "Event Calendar", ok, note)

    # -- 13. Financial results ------------------------------------------------
    # The old call passed no `period`, and NSE answered with a stale default
    # slice: 6 rows spanning 2005-2010 for RELIANCE, which is why the archive
    # was stuck at 2007-2012. Probed against the live API 2026-07-27:
    #     no params        ->   6 rows, Sep-2005 .. Sep-2010
    #     period=Quarterly -> 130 rows, Jun-2005 .. Mar-2024   <-- use this
    #     period=Annual    ->  39 rows, Mar-2005 .. Mar-2024
    # Adding from_date/to_date actually NARROWS the result (122 rows), so the
    # bare period parameter is what we want.
    step(13, "Financial Results (Quarterly + Annual, per symbol)")
    fr_frames, fr_fail = [], 0
    for i, sym in enumerate(symbols):
        got_any = False
        for period in ("Quarterly", "Annual"):
            ok, payload = fetch_json(
                f"{API}/corporates-financial-results",
                params={"index": "equities", "symbol": sym, "period": period},
                retries=2, delay=0.3)
            if ok:
                rows = normalize_rows(payload)
                if rows:
                    got_any = True
                    for r in rows:
                        r.setdefault("symbol", sym)
                        r.setdefault("company_name", symbol_map.get(sym, sym))
                        r.setdefault("resultPeriod", period)
                    fr_frames.append(pd.DataFrame(rows))
            time.sleep(0.2)
        if not got_any:
            fr_fail += 1
        if (i + 1) % 25 == 0:
            get_session(force=True)
    if fr_frames:
        df = pd.concat(fr_frames, ignore_index=True)
        save_feed(df, "13_Financial_Results.xlsx", "Financial Results", True,
                  f"{len(df)} rows from {len(symbols) - fr_fail}/{len(symbols)} symbols")
    else:
        save_feed(pd.DataFrame(), "13_Financial_Results.xlsx", "Financial Results",
                  False, "no symbol returned results for either period")

    # -- 14. Financial results comparison -------------------------------------
    step(14, "Financial Results Comparison")
    df, ok, note = harvest(f"{API}/results-comparision", universe_set=universe_set)
    save_feed(df, "14_Financial_Results_Comparison.xlsx",
              "Financial Results Comparison", ok, note)

    # -- 15. Further issues / QIP ---------------------------------------------
    step(15, "Further Issues XBRL Filings")
    df, ok, note = harvest(f"{API}/corporate-further-issues-qip?index=FIQIPIP",
                           universe_set=universe_set)
    save_feed(df, "15_Further_Issues_XBRL_Filings.xlsx", "Further Issues XBRL", ok, note)

    # -- 16. Insider trading (PIT) --------------------------------------------
    # Was returning nothing for months. The endpoint answers {"acqNameList": [],
    # "data": []} with no date window — the old code read that as "no records"
    # and logged SUCCESS. Probed 2026-07-27: a rolling ONE-YEAR window returns
    # 10,601 rows. Kept MARKET-WIDE (not universe-filtered) on purpose: insider
    # disclosures are most informative in mid/small caps, and it is one call.
    step(16, "Insider Trading (PIT) — rolling 1-year window, market-wide")
    today = datetime.now()
    df, ok, note = harvest(f"{API}/corporates-pit", params={
        "index": "equities",
        "from_date": today.replace(year=today.year - 1).strftime("%d-%m-%Y"),
        "to_date": today.strftime("%d-%m-%Y"),
    })
    save_feed(df, "16_Insider_Trading_PIT.xlsx", "Insider Trading", ok, note)

    # -- 17. Insider trading plan ---------------------------------------------
    step(17, "Insider Trading Plan")
    df, ok, note = harvest(f"{API}/corporate-shareholding-disclosure", params={
        "type": "reg5",
        "from_date": today.replace(year=today.year - 1).strftime("%d-%m-%Y"),
        "to_date": today.strftime("%d-%m-%Y"),
    })
    save_feed(df, "17_Insider_Trading_Plan.xlsx", "Insider Trading Plan", ok, note)

    # -- 18. Investor complaints ----------------------------------------------
    step(18, "Investor Complaints")
    df, ok, note = harvest(f"{API}/investor-complaints?index=equities", universe_set=universe_set)
    save_feed(df, "18_Investor_Complaints.xlsx", "Investor Complaints", ok, note)

    # -- 19. Issue / offer documents ------------------------------------------
    step(19, "Issue Offer Documents")
    df, ok, note = harvest(f"{API}/offer-documents")
    save_feed(df, "19_Issue_Offer_Documents.xlsx", "Issue Offer Documents", ok, note)

    # -- 20. Promoter encumbrance ---------------------------------------------
    step(20, "Promoter Encumbrance Details")
    df, ok, note = harvest(f"{API}/corporate-pledgedata-sast3132", universe_set=universe_set)
    save_feed(df, "20_Promoter_Encumbrance_Details.xlsx", "Promoter Encumbrance", ok, note)

    # -- 21. Related party transactions ---------------------------------------
    step(21, "Related Party Transactions")
    df, ok, note = harvest(f"{API}/related-party-transactions-master?index=equities",
                           universe_set=universe_set)
    save_feed(df, "21_Related_Party_Transactions.xlsx", "Related Party Transactions",
              ok, note)

    # -- 22. SAST regulations --------------------------------------------------
    step(22, "SAST Regulations")
    df, ok, note = harvest_symbol_wise(
        f"{API}/corporate-sast-reg29?index=equities&symbol={{symbol}}",
        symbols, symbol_map, key_in_resp="data")
    save_feed(df, "22_SAST_Regulations.xlsx", "SAST Regulations", ok, note)

    # -- 23. Secretarial compliance -------------------------------------------
    step(23, "Secretarial Compliance")
    df, ok, note = harvest(f"{API}/secretarial-report?index=equities", universe_set=universe_set)
    save_feed(df, "23_Secretarial_Compliance.xlsx", "Secretarial Compliance", ok, note)

    # -- 24. Share transfers ---------------------------------------------------
    step(24, "Share Transfers")
    df, ok, note = harvest(f"{API}/corporate-sharetransfer-equities-dates",
                           universe_set=universe_set)
    save_feed(df, "24_Share_Transfers.xlsx", "Share Transfers", ok, note)

    # -- 25. Shareholders' meetings --------------------------------------------
    step(25, "Shareholder Meetings")
    df, ok, note = harvest(f"{API}/postal-ballot?index=equities", universe_set=universe_set)
    save_feed(df, "25_Shareholders_Meetings.xlsx", "Shareholder Meetings", ok, note)

    # -- 26. Shareholding pattern ----------------------------------------------
    step(26, "Shareholding Pattern")
    df_shp, shp_ok, note = harvest(f"{API}/corporate-share-holdings-master?index=equities",
                                   universe_set=universe_set)
    save_feed(df_shp, "26_Shareholding_Pattern.xlsx", "Shareholding Pattern", shp_ok, note)

    # -- 27. Shareholding pattern SDD ------------------------------------------
    step(27, "Shareholding Pattern SDD")
    df, ok, note = harvest(f"{API}/shareholding-patterns-sdd?index=equities",
                           universe_set=universe_set)
    save_feed(df, "27_Shareholding_Pattern_SDD.xlsx", "Shareholding Pattern SDD", ok, note)

    # -- 28. Statement of deviation --------------------------------------------
    step(28, "Statement of Deviation / Variation")
    df, ok, note = harvest(f"{API}/statement-deviation-master?index=equities",
                           universe_set=universe_set)
    save_feed(df, "28_Statement_of_Deviation.xlsx", "Statement of Deviation", ok, note)

    # -- 29. Audit qualification impact ----------------------------------------
    step(29, "Statement of Impact of Audit Qualification")
    df, ok, note = harvest(f"{API}/details-sod", universe_set=universe_set)
    save_feed(df, "29_Audit_Qualification_Impact.xlsx", "Audit Qualification Impact",
              ok, note)

    # -- 30. SDD - PIT ----------------------------------------------------------
    step(30, "System Driven Disclosures - PIT")
    df, ok, note = harvest(f"{API}/corpreg7?index=equities", universe_set=universe_set)
    save_feed(df, "30_System_Driven_Disclosures_PIT.xlsx", "SDD PIT", ok, note)

    # -- 31. SDD - SAST ---------------------------------------------------------
    step(31, "System Driven Disclosures - SAST")
    df, ok, note = harvest(f"{API}/corporate-shareholding-disclosure?type=reg29",
                           universe_set=universe_set)
    save_feed(df, "31_System_Driven_Disclosures_SAST.xlsx", "SDD SAST", ok, note)

    # -- 32. Voting results -----------------------------------------------------
    step(32, "Voting Results")
    df, ok, note = harvest_symbol_wise(
        f"{API}/corporate-voting-results?index=equities&symbol={{symbol}}",
        symbols, symbol_map)
    save_feed(df, "32_Voting_Results.xlsx", "Voting Results", ok, note)

    # -- 33. FII / DII activity -------------------------------------------------
    step(33, "FII / DII Daily Trading Activity")
    df, ok, note = harvest(f"{API}/fiidiiTradeReact")
    save_feed(df, "33_FII_DII_Trading_Activity.xlsx", "FII DII Trading Activity", ok, note)

    # -- 34 / 35. Bulk & block deals --------------------------------------------
    for n, label, fname, sheet, url in (
        (34, "Bulk Deals", "34_Bulk_Deals.xlsx", "Bulk Deals",
         "https://nsearchives.nseindia.com/content/equities/bulk.csv"),
        (35, "Block Deals", "35_Block_Deals.xlsx", "Block Deals",
         "https://nsearchives.nseindia.com/content/equities/block.csv"),
    ):
        step(n, label)
        try:
            r = get_session().get(url, headers=HEADERS, timeout=20)
            r.raise_for_status()
            from io import StringIO
            d = pd.read_csv(StringIO(r.text))
            save_feed(d, fname, sheet, True, f"{len(d)} rows from CSV")
        except Exception as e:
            save_feed(pd.DataFrame(), fname, sheet, False, f"{type(e).__name__}: {e}")

    # -- 36. Concall transcripts & presentations (derived from #2) --------------
    # Previously re-fetched announcements for symbols[:15] only, so 35 of the 50
    # Nifty constituents were silently skipped. Derive from #2 instead.
    step(36, "Concall Transcripts & Investor Presentations (derived from #2)")
    if ann_ok and not df_ann.empty:
        kw = ["transcript", "presentation", "concall", "earnings call", "analyst meet"]
        blob = (df_ann.get("desc", "").astype(str) + " " +
                df_ann.get("attchmntText", "").astype(str)).str.lower()
        hit = df_ann[blob.str.contains("|".join(kw), na=False, regex=True)].copy()
        hitblob = blob[hit.index]
        if hit.empty:
            save_feed(pd.DataFrame(), "36_Concall_Transcripts_Presentations.xlsx",
                      "Concalls & Presentations", True, "no matching announcements")
        else:
            files = hit.get("attchmntFile", pd.Series("", index=hit.index)).astype(str)
            links = files.apply(lambda f: f if f.startswith("http") or not f
                                else f"https://nsearchives.nseindia.com/corporate/{f}")
            d = pd.DataFrame({
                "Symbol": hit["symbol"],
                "Company Name": hit.get("company_name", hit["symbol"]),
                "Date": hit.get("an_dt"),
                "Category": hitblob.str.contains("presentation").map(
                    {True: "Presentation", False: "Transcript"}),
                "Description": hit.get("desc"),
                "Attachment Text": hit.get("attchmntText"),
                "PDF Download Link": links,
                "BroadCast Time": hit.get("exchdisstime"),
            })
            save_feed(d, "36_Concall_Transcripts_Presentations.xlsx",
                      "Concalls & Presentations", True,
                      f"{len(d)} hits across all {df_ann['symbol'].nunique()} symbols")
    else:
        save_feed(pd.DataFrame(), "36_Concall_Transcripts_Presentations.xlsx",
                  "Concalls & Presentations", ann_ok, "source feed #2 unavailable")

    # -- 37. Credit rating reports ----------------------------------------------
    step(37, "Credit Rating Reports")
    df, ok, note = harvest(f"{API}/credit-rating-sdd-reg30?index=equities",
                           universe_set=universe_set)
    save_feed(df, "37_Credit_Rating_Reports.xlsx", "Credit Rating Reports", ok, note)

    # -- 38. Super investor / institutional holdings ------------------------------
    # NOTE: same endpoint as #26. Kept separate so neither archive loses history.
    step(38, "Super Investor & Institutional Shareholding")
    save_feed(df_shp, "38_Super_Investor_Institutional_Holdings.xlsx",
              "Super Investor & Inst Holdings", shp_ok,
              note if shp_ok else "shared fetch with #26 failed")

    summarise()


# ---------------------------------------------------------------------------
def summarise():
    ok = [f for f, s in RUN_STATUS.items() if s["status"] == "OK"]
    empty = [f for f, s in RUN_STATUS.items() if s["status"] == "EMPTY"]
    fail = [f for f, s in RUN_STATUS.items() if s["status"] == "FAIL"]

    print("\n" + "=" * 78)
    print(f"  RUN SUMMARY — {RUN_TS}" + ("  [DRY RUN — nothing written]" if DRY_RUN else ""))
    print("=" * 78)
    print(f"  {'feed':<46} {'status':<7} {'fetched':>8} {'archive':>9}")
    print("-" * 78)
    for feed in sorted(RUN_STATUS):
        s = RUN_STATUS[feed]
        print(f"  {feed:<46} {s['status']:<7} {s['fetched']:>8} {s['archive_rows']:>9,}")
    print("-" * 78)
    print(f"  OK {len(ok)}   EMPTY {len(empty)}   FAIL {len(fail)}   of {len(RUN_STATUS)} feeds")

    if fail:
        print("\n  NEEDS ATTENTION — these did not fetch (archive untouched):")
        for f in fail:
            print(f"    ! {f}: {RUN_STATUS[f]['note']}")
    if empty:
        print("\n  EMPTY — endpoint answered but returned no rows:")
        for f in empty:
            print(f"    - {f}: {RUN_STATUS[f]['note']}")
    print("=" * 78)

    if not DRY_RUN:
        try:
            with open(STATUS_FILE, "w", encoding="utf-8") as fh:
                json.dump({"run": RUN_TS, "ok": len(ok), "empty": len(empty),
                           "fail": len(fail), "feeds": RUN_STATUS}, fh, indent=2)
            print(f"  Machine-readable status -> {STATUS_FILE}")
        except Exception as e:
            print(f"  [WARN] could not write status file: {e}")


if __name__ == "__main__":
    run_scraper()
